### ISSUE TITLE
Step 7 error

### ISSUE THREAD

**Issue by kdurston** [WASdev/sample.microservicebuilder.docs#8]
During Step 7, I got the following error:
$ cd ../*vote
$ helm install --name=vote chart/microservice-vote
Error: release vote failed: PersistentVolume "cloudant-pvc" is invalid: spec.capacity[storage]: Invalid value: "0": must be greater than zero

**Comment by davidcurrie** [comment]
Should be addressed by https://github.com/WASdev/sample.microservicebuilder.vote/pull/13/files
